### PR TITLE
remove need for setting build config

### PR DESCRIPTION
**Pull request by mathe42**
With PR the the build options are not needed anymore! They are set directly by the plugin.

### CODE REVIEW

**Comment by richardtallent** [comment]
I like the idea, but I'm a little concerned that there *may* be people out there using this plugin with slightly different settings.

Would this prevent someone from using their own settings, if for some reason they need to? I'm not familiar enough with the plugin architecture.

**Comment by Greenheart** [comment]
How about including this behind a config option?

In all my vite projects so far, I've never had to touch vite's build config except to add the settings that `vite-plugin-singlefile` recommends. I think this is pretty common for most projects.

Thus, I think it would be safe to add this feature behind a config option (see #26 for details).

If we make this a default option (released as a semver breaking 0.9.0), and include clear documentation for how to disable this via the plugin config, then we could greatly simplify the plugin usage for most projects.

Imagine if we could simplify the usage example of `vite-plugin-singlefile` from the current example which can be intimidating for beginners:

---

## How do I use it?

Here's an example `vite.config.ts` file.

```ts
import { defineConfig } from "vite"
import vue from "@vitejs/plugin-vue"
import { viteSingleFile } from "vite-plugin-singlefile"

export default defineConfig({
	plugins: [vue(), viteSingleFile()],
	build: {
		target: "esnext",
		assetsInlineLimit: 100000000,
		chunkSizeWarningLimit: 100000000,
		cssCodeSplit: false,
		brotliSize: false,
		rollupOptions: {
			inlineDynamicImports: true,
			output: {
				manualChunks: () => "everything.js",
			},
		},
	},
})
```

...and then transform the usage example into this:


## How do I use it?

Add `viteSingleFile()` at the end of your vite plugins.

Here's an example `vite.config.ts` file:

```ts
import { defineConfig } from "vite"
import vue from "@vitejs/plugin-vue"
import { viteSingleFile } from "vite-plugin-singlefile"

export default defineConfig({
	plugins: [vue(), viteSingleFile()],
})
```

**Comment by mathe42** [comment]
Is fine for me. My internal Plugins often change some config. 😉

**Comment by richardtallent** [comment]
I missed this for 0.8.0, but will look again...

**Comment by Greenheart** [comment]
Since I have no push access to this branch, I created an updated PR that makes this behavior possible to enable/disable with a config option.

Thanks @mathe42 for sharing this idea! This will make a huge difference to how end-users perceive the plugin 😄

**Comment by mathe42** [comment]
Lgtm

**Pull request closed without merging**
