### PR TITLE
Bump deps, and allows open range peer dependencies 

### LINKED ISSUE #104: Compatibility with Vite 6
I'm getting the following error message when running `npm install` after updating the `vite` dependency to 6.0.0:

```
npm error While resolving: vite-plugin-singlefile@2.0.3
npm error Found: vite@6.0.0
npm error node_modules/vite
npm error   dev vite@"6.0.0" from the root project
npm error   peer vite@"^5.0.0 || ^6.0.0" from @vitejs/plugin-vue@5.2.1
npm error   node_modules/@vitejs/plugin-vue
npm error     dev @vitejs/plugin-vue@"5.2.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vite@"^5.4.10" from vite-plugin-singlefile@2.0.3
npm error node_modules/vite-plugin-singlefile
npm error   dev vite-plugin-singlefile@"2.0.3" from the root project
npm error
npm error Conflicting peer dependency: vite@5.4.11
npm error node_modules/vite
npm error   peer vite@"^5.4.10" from vite-plugin-singlefile@2.0.3
npm error   node_modules/vite-plugin-singlefile
npm error     dev vite-plugin-singlefile@"2.0.3" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

Does the plugin work with 6.0.0? Do you have plans to update the peer dependency?

### PR DESCRIPTION
**Pull request by slebs**
Bump deps, and allows open range peer dependencies 

Added very loosely defined peer dependency ranges that include anything newer than what was supported before

closes #104

### CODE REVIEW

**Review by richardtallent — APPROVED** [review]
Accepted, but I'll be rolling back the Node 22 dependency and going from open range to the range actually supported

**Comment by reintroducing** [comment]
@richardtallent thanks for the quick turnaround on this. As your release notes state, it does not work without a force, which isn't ideal. I'm curious, why was vitest added as a dependency in the PR or your updates anyway? what is it needed for? And also, its listed as a devDependency, so I'm not sure why it would be causing downstream dependency checking either. Did I miss something that is causing this?

**Comment by richardtallent** [comment]
Vitest is needed as a dev dependency to run the plugin's tests, which I do prior to publishing new versions.

To run the tests and ensure vite 6 didn't break anything, vite 6 has to be the version installed locally.

To run vite 6, vitest 3.0.0-beta.1 is needed, because 2.x is not compatible with vite 6. The beta version is intended to be expressly for vite 6, but they failed to allow vite 6 in one of vitest 3's own libraries, causing the need to force.

This shouldn't be an issue for anyone just *using* this plugin with vite 6, only for the handful of folks like me testing the plugin.

Of course, anyone using vitest with vite 6 will independently see this issue as well until the vitest folks fix and release a new patch. I didn't have time to check to see if it's a known issue yet.

(Side note: it would be great if there were a way to run the tests in both vite 6 /vitest 3 and vite 5 / vitest 2 to ensure tests run identically under both, but I also didn't have a chance to see if I could figure out how to do that. I suspect not without a more complicated harness script.)

**Comment by reintroducing** [comment]
Gotcha, I was confused because Vitest was not a dependency pre-the aforementioned PR that was listed at all, so I suspect maybe it was just forgotten previously to be listed as a devDependency?

That being said, I don't use Vitest in my project at all but was getting issues installing Vite 6 + the version of the plugin you just published (2.1) and could not proceed without forcing, which is where the confusion stems from. Therefore, I am not sure that this statement holds true: `This shouldn't be an issue for anyone just using this plugin with vite 6, only for the handful of folks like me testing the plugin.`

**Comment by richardtallent** [comment]
Vitest has been around this library as a dev dependency for awhile -- see line 61 of the PR (https://github.com/richardtallent/vite-plugin-singlefile/pull/105/files).

The plugin itself *should* allow either vite 5 or 6:

https://github.com/richardtallent/vite-plugin-singlefile/blob/3514043f41bbac3c1736647000588cae02d6ea7f/package.json#L52

If you're not using vitest or anything else that isn't compatible with vite 6, I can't see a reason why it would have a problem. Can you post the fresh-cloned `npm i` message as a separate Issue and reference this conversation?

**Comment by reintroducing** [comment]
@richardtallent You can ignore me, I'm not sure what happened last night when I was doing this but between updating a bunch of random dependencies throughout my project I must have gotten into a state where I was getting an error (maybe I forgot to clear my package lock or node_modules at some point when doing this). I just tried this morning, first by starting a new vite project from scratch and installing the plugin (which worked fine), and then I just tried it again in my project after bumping the deps and all was well. Not sure what happened but I'm good to go. Thank you for this update and for humoring my idiocy last night, truly appreciated. My apologies for the time suck :)

**Pull request merged**
