### PR TITLE
feat: remove unused Vite module loader

### PR DESCRIPTION
**Pull request by Z233**
For this issue: #9

### CODE REVIEW

**Comment by richardtallent** [comment]
Seems like a micro-optimization, and I'm a little concerned that it could be brittle and might break easily as Vite itself is updated. I'm not necessarily against adding it, just concerned and haven't had a chance to dig into it.

**Comment by Greenheart** [comment]
I've been using this approach reliably for more than a year in 10+ different projects. So far, it's changed one time, and the update process was pretty straightforward. [Updated regex here](https://github.com/Greenheart/pagecrypt/blob/main/scripts/postbuild.js#L29-L36)


## Next steps for this PR:

If we add this behind an opt-in config, we could let the default behavior remain the same and avoid breaking existing projects where people are unaware of this optimization.

```ts
// vite.config.js
{
  plugins: [viteSingleFile({ removeViteModuleLoader: true })]
}
```

**Comment by richardtallent** [comment]
An opt-in sounds good. Do you have time to update the PR for the new regex and to resolve conflicts and add this info to the README?

**Comment by Greenheart** [comment]
Sure, I'll see what I can do 👍

**Comment by Greenheart** [comment]
Thanks @Z233 for encouraging development of this feature! It's ready for review in #26

**Pull request closed without merging**
